name: learn-github-actions # comment
on: [push] # comment
jobs: # comment
  check-bats-version: # comment
    runs-on: ubuntu-latest # comment
    steps: # comment
      - uses: actions/checkout@v4 # comment
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
